name: server
description: A server app using the shelf package.
version: 1.0.0

environment:
  sdk: ^3.10.8

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.3
  sqlite3: ^3.1.1
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.6
  extra_lints:
    git:
      url: https://github.com/mitulvaghamshi/extra_lints.git
  http: ^1.1.0
  test: ^1.24.0
