name: console
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.10.8

dev_dependencies:
  extra_lints:
    git:
      url: https://github.com/mitulvaghamshi/extra_lints.git
  test: ^1.24.0
